name: Auto Request Reviewer

on:
  pull_request:
    branches:
      - main
    types: [opened, ready_for_review]

jobs:
  call-the-lords:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouut repo
        uses: actions/checkout@v4

      - name: assign reviewers to PR
        uses: kentaro-m/auto-assign-action@v2.0.0
